### ISSUE TITLE
URL / homepage is not parsed

### ISSUE THREAD

**Issue by kasicka** [theforeman/npm2rpm#11]
'homepage' field in package.json isn't parsed, so URL in resulting spec file is undefined.

**Comment by dLobatog** [comment]
Which package are you trying to parse? I've tried with a few and it seems to work. bin/npm2rpm.js is what takes care of that

**Comment by kasicka** [comment]
I tried async and abbrev and few other modules that I don't remember now.

**Comment by kasicka** [comment]
After little investigation I discovered that URLs containing # aren't parsed. When I tried express or webpack, which have their own websites, the homepage was parsed normally.
Maybe url from bugs could be parsed while this gets fixed.

**Comment by dLobatog** [comment]
Oh that's it, https://github.com/caolan/async/blob/master/package.json doesn't have a homepage even, so we have to look into 'bugs', 'url' :smile:

**Comment by kasicka** [comment]
I was trying `npm v async homepage` where it showed homepage, not actually reading the package.json :D

**Comment by ekohl** [comment]
https://github.com/lydell/js-tokens/blob/master/package.json just has a string for repository, most likely a github URL.

**Comment by ekohl** [comment]
We use https://www.npmjs.com/package/normalize-package-data now which I think handles this well. Feel free to reopen or open a new issue if there's still cases that aren't parsed properly.
