### ISSUE TITLE
Not specifying -v option results in ugly error

### ISSUE THREAD

**Issue by kasicka** [theforeman/npm2rpm#12]
IMHO -v should be optional and by default latest version should be packaged. However, when it is not specified, it results in

```
 - Starting npm module download: http://registry.npmjs.org/async/-/async-function (str, flags) {
  if (0 == arguments.length) return this._version;
  this._version = str;
  flags = flags || '-V, --version';
  this.option(flags, 'output the version number');
  this.on('version', function() {
    process.stdout.write(str + '\n');
    process.exit(0);
  });
  return this;
}.tgz
 - Unpacking in /tmp/npm2rpm-8861LnRPHyiKdhKx ...
{ Error: incorrect header check
    at Zlib._handle.onerror (zlib.js:370:17) errno: -3, code: 'Z_DATA_ERROR' }

```

**Comment by dLobatog** [comment]
Should be "fixed"  with ff9ecb05b331a2786549230e2e8378455d878780 . I do agree it'd be nice to download the latest version, however I'm a bit reluctant to code more until I have a test suite for what I have already, so this will have to wait a bit :disappointed:  I'd accept a PR with the feature gladly, though!
