### ISSUE TITLE
Source tarball isn't downloaded to SOURCES

### ISSUE THREAD

**Issue by kasicka** [theforeman/npm2rpm#13]
I see it gets downloaded and extracted to /tpm, but it doesn't end up in npm2rpm/SOURCES (or at least it never did when I tried with multiple modules).

**Comment by dLobatog** [comment]
On 08/25, Zuzana Svetlíková wrote:

> I see it gets downloaded and extracted to /tpm, but it doesn't end up in npm2rpm/SOURCES (or at least it never did when I tried with multiple modules).

There's a bug in the current code, it downloads it when the strategy is
'bundle', but not when it's 'single'. Most important TODO right now :)

> ## 
> 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/dLobatog/npm2rpm/issues/13

## 

Daniel Lobato Garcia

@dLobatog
blog.daniellobato.me
daniellobato.me

GPG: http://keys.gnupg.net/pks/lookup?op=get&search=0x7A92D6DD38D6DE30
Keybase: https://keybase.io/elobato

**Comment by dLobatog** [comment]
Done via84ec07c7ded3ecb58e33590503664879702047d8 , 2.1.3 has it
