### ISSUE TITLE
Use a templating engine for the spec file template

### ISSUE THREAD

**Issue by domcleal** [theforeman/npm2rpm#18]
It would be very useful if the spec file template was rendered with a proper templating engine, which would allow for conditionals, loops etc in the spec file. Currently much of the logic resides in the program which reduces what changes can be made in the template.

It may help to solve #17 if the template could contain conditionals such as "if bundle".

**Comment by dLobatog** [comment]
Any suggestions for a templating language to use? All that I found for javascript was basically engines to embed javascript in HTML or JSON, sounds like a stretch to use these kind of things for a spec.

In any case you'd want to pass data structures like maps, arrays, etc.. to the template spec so they are resolved during template rendering?

**Comment by domcleal** [comment]
Sorry, no suggestions. Ideally something like ERB (used by [gem2rpm](https://github.com/fedora-ruby/gem2rpm/tree/master/templates)) and yes, to access data structures too.

**Comment by domcleal** [comment]
[nunjucks](http://mozilla.github.io/nunjucks/) and even [ejs](https://www.npmjs.com/package/ejs) look like they'd work OK for non-HTML/JSON outputs.

**Comment by dLobatog** [comment]
https://github.com/dLobatog/npm2rpm/pull/35 tries to solve this

**Comment by ekohl** [comment]
Since https://github.com/dLobatog/npm2rpm/commit/3c028402250d09958fba3db421ccee287d41cd20 we use handlebars for templates.
