### ISSUE TITLE
Missing binaries causes: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by domcleal** [theforeman/npm2rpm#2]
Building jquery-flot 0.8.3 again, the following error's received:

<pre>
# node_modules/.bin/npm2rpm -n jquery-flot -v 0.8.3 -s single
---- npm2rpm ----
-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-
 - Starting npm module download: http://registry.npmjs.org/jquery-flot/-/jquery-flot-0.8.3.tgz
 - Unpacking in /tmp/npm2rpm-33615TXHgRe74h06 ...
 - Finished extracting for jquery-flot
 - Reading package.json for jquery-flot
 - Finished reading package.json for jquery-flot
 - Fetching flattened list of production dependencies
Cannot read property 'length' of undefined
</pre>

Possibly because the package has no prod dependencies listed, not even an empty array in the package.json?

<pre>
{
        "name": "jquery-flot",
        "version": "0.8.3",
        "main": "jquery.flot.js",
        "scripts": {
                "test": "make test"
        },
        "devDependencies": {
                "jshint": "0.9.1"
        }
}
</pre>

**Comment by dLobatog** [comment]
This should've been fixed with fa5f8badffa4675f7688046cca7f4206a5522d61 , let me know if that's not the case. Thanks for the report!
