### ISSUE TITLE
getBaseName is not defined

### ISSUE THREAD

**Issue by dayer3** [theforeman/npm2rpm#20]
Hi,
I'm getting this error and I've found [the related line](https://github.com/dLobatog/npm2rpm/blob/master/lib/spec_file_generator.js#L69).
The **lib/spec_file_generator.js** is calling to `getBaseName` function, but I only find `getBasename` in the rest of the file.
Do you know if I need another module or is it a syntax error?
Regards,

**Comment by dLobatog** [comment]
It's a typo  - thanks for noticing. I'll fix it and push a new patch version right away. Thanks @dayer3 !

**Comment by dLobatog** [comment]
Released as 2.1.6 - thanks again for reporting this @dayer3 :smile:
