### ISSUE TITLE
Generate tarballs for different npm versions

### ISSUE THREAD

**Issue by dLobatog** [theforeman/npm2rpm#37]
Different npm versions generate different cache tarballs. Ideally we should be able to pass an option `--cache-version` which contains the version of NPM we want the cache for. E.g: "3.x"

**Comment by ekohl** [comment]
Because the caching appears to be consistent since 3.x I'm leaning to closing this until there's an actual need for it.

**Comment by ekohl** [comment]
Closing this and we can reopen it if needed
