### ISSUE TITLE
Download packages with "/" in its name

### ISSUE THREAD

**Issue by kekePower** [theforeman/npm2rpm#40]
Hi.

I'm trying to convert https://www.npmjs.com/package/@sellside/emitter to rpm, but am unable to.

Do you have any ideas on how I can achieve this?

TIA.

**Comment by ekohl** [comment]
It needs some conversion convention. So far we haven't created RPMs with `@` or `/` and I think both are not allowed in RPM package names. My first thought is to drop `@` and replace `/` with `-` but I can't really oversee the consequences on overlapping package names. Anyone has thoughts on this?

**Comment by kekePower** [comment]
Thanks for getting back to me.

I think replacing the / with - is a good idea. That's what I plan on naming my package in Mageia since it's impossible to have a / in the name anyway.
Another option, of course, is to use underscore as the delimiter.

Example: nodejs-sellside_emitter

I tried several options to download the package, but none of them worked. If I could only download the package, I could create the rpm spec manually.

**Comment by dLobatog** [comment]
@kekePower https://github.com/dLobatog/npm2rpm/pull/42 got merged

**Comment by ekohl** [comment]
@dLobatog it handles it with bundled dependencies - no idea if it works for actual package names since I haven't tried that.

**Comment by ohadlevy** [comment]
it seems this fails on packages them self, e.g. try to add @novnc/novnc.
